### PR TITLE
CP-309 chore: bumped SWR version to 1.1.2

### PR DESCRIPTION
**Pull request by xiyan128**

### CODE REVIEW

**Comment by xiyan128** [comment]
Seems like there's no breaking changes. Just changed a version number.

**Comment by 634750802** [comment]
@xiyan128 please do some simple tests in preview env

**Comment by cw1997** [comment]
Why do we need to bump SWR version now? Because we want to use some new features?

**Comment by 634750802** [comment]
align with https://github.com/pingcap-inc/tidb-community-ui

**Comment by 634750802** [comment]
@xiyan128 did it tested?

**Comment by xiyan128** [comment]
@634750802 Tested OK

**Review by 634750802 — APPROVED** [review]

**Pull request merged**
